name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        working-directory: ./src/ratingservice
        run: go build -v ./...

      - name: Test
        working-directory: ./src/ratingservice
        run: go test -v ./...